# Unique name of this workflow
name: sfpowerscripts release

on:
    workflow_dispatch:
    push:
        branches:
            - release 
            - release/*

jobs:  
    build:
        name: Build packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

              # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
                  sfdx auth:jwt:grant -u ${{ secrets.DEVHUB_USERNAME }} -i ${{ secrets.DEVHUB_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
                  rm -f ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

              # Create all packages
            - name: 'Create packages'
              id: sfpowerscripts-build
              run: 'sfdx sfpowerscripts:orchestrator:build -v devhub -f config/project-scratch-org.json --branch master'

              # Publish artifacts
            - uses: actions/upload-artifact@v2
              with:
                  name: validated-artifacts
                  path: artifacts

    promote:
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        name: Promote the packages
        needs: build
        environment:
            name: Promote
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

              # Download Artifacts

            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: validated-artifacts
                  path: artifacts

            # Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
                  sfdx auth:jwt:grant -u ${{ secrets.DEVHUB_USERNAME }} -i ${{ secrets.DEVHUB_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com
                  rm -f ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.DEVHUB_SERVER_KEY }}

            # Promoted all packages
            - name: 'Promote packages'
              id: sfpowerscripts-build
              run: 'sfdx sfpowerscripts:orchestrator:promote -v devhub -o promoted-artifacts'

            # Publish artifacts
            - uses: actions/upload-artifact@v2
              with:
                  name: promoted-artifacts
                  path: promoted-artifacts

    publish:
        name: Publish artifacts to GitHub Packages
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        needs: promote
        steps:
            # Checkout the code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: promoted-artifacts
                  path: promoted-artifacts

            - name: Set NPM registry
              run: |
                  npm set registry https://npm.pkg.github.com
            - name: Authenticate to NPM registry
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${AUTH_TOKEN}" >> ~/.npmrc
              env:
                  AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish
              run: |
                  sfdx sfpowerscripts:orchestrator:publish -d promoted-artifacts --npm --scope Craft-First --gittag --pushgittag --npmtag LATEST