# Unique name for this workflow
name: sfpowerscripts validate

# Definition when the workflow should run
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - master


# Jobs to be executed
jobs:
    validate:
        runs-on: ubuntu-latest
        container: dxatscale/sfpowerscripts
        steps:
            # Checkout the code in the pull request
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            # Copy Dev Hub server key to file
            - name: 'Copy Dev Hub server key to file'
              shell: bash
              run: |
                  echo "${SALESFORCE_JWT_SECRET_KEY}" > ./JWT_KEYFILE
              env:
                  SALESFORCE_JWT_SECRET_KEY: ${{ secrets.MA_SERVER_KEY }}

            # Authorised Org
            - name: 'Authenicate Org'
              run: 'sfdx auth:jwt:grant -u ${{ secrets.MA_USERNAME }} -i ${{ secrets.MA_CLIENT_ID }} -f ./JWT_KEYFILE -a devhub -r https://login.salesforce.com'

            # Create Scratch Org
            - name: 'Create New Scratch Org'
              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 -v devhub

            # Install Package Dependicies to Org
            - name: 'Install Package Dependencies to Org'
              run: 'sfdx sfpowerkit:package:dependencies:install -u scratch-org -v devhub -r'

            # Validate Against Org
            - name: 'Push source to scratch org'
              run: 'sfdx sfpowerscripts:orchestrator:validateAgainstOrg -u scratch-org'

            # Delete Scratch Org
            - name: 'Delete Scratch Org'
              run: 'sfdx force:org:delete -p -u scratch-org'
